<a href="https://colab.research.google.com/github/samantafe8-collab/Ciencia-datos-curso/blob/main/tarea_01_python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [ ]:
# Tu respuesta aquí
nombre ="daniela"
edad= 34

print("Hola, me llamo ",nombre," y tengo ",edad,"años")

Hola, me llamo  daniela  y tengo  34 años


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [ ]:
numeros = [10, 25, 3, 47, 8, 15]

# Tu respuesta aquí
print("El primer número es",numeros[0]," y ","el último número es",numeros[5] )
print("Los primeros 3 números son", numeros[0:3])
numeros.append(99)
print(numeros)

El primer número es 10  y  el último número es 15
Los primeros 3 números son [10, 25, 3]
[10, 25, 3, 47, 8, 15, 99]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [ ]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

# Tu respuesta aquí

if estudiante["promedio"] >= 6:
    print("Aprobado")
else:
    print("Reprobado")

Aprobado


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [ ]:
# Tu respuesta aquí

base =5
altura = 8
calcular_area= (base*altura)/2

print("El área del triángulo es", calcular_area)

El área del triángulo es 20.0


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [ ]:
# Tu respuesta aquí

cuadrados = [x**2 for x in range(1, 11)]

print("Los cuadrados de los número del 1 al 10 son:", cuadrados)

Los cuadrados de los número del 1 al 10 son: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


---
## Parte 2 — NumPy

In [ ]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [ ]:
# Tu respuesta aquí
# Arreglo con los valores
x = np.array([1.5, 2.5, 3.5, 4.5])
print("Arreglo 1:", x)
print("Shape:", x.shape, "| dtype:", x.dtype)

# Matriz de ceros 3*4
m_ceros = np.zeros((3, 4))
print("\nMatriz de ceros:\n", matriz_ceros)
print("Shape:", matriz_ceros.shape, "| dtype:", matriz_ceros.dtype)

# Arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando linspace)
arreglo_lin = np.linspace(0, 1, 6)
print("\nArreglo linspace:", arreglo_lin)
print("Shape:", arreglo_lin.shape, "| dtype:", arreglo_lin.dtype)

Arreglo 1: [1.5 2.5 3.5 4.5]
Shape: (4,) | dtype: float64

Matriz de ceros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4) | dtype: float64

Arreglo linspace: [0.  0.2 0.4 0.6 0.8 1. ]
Shape: (6,) | dtype: float64


**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [ ]:
a = np.arange(1, 13)

# Tu respuesta aquí
matriz = a.reshape(3, 4)
print("Matriz resultante:\n", matriz)

Matriz resultante:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [ ]:
# Tu respuesta aquí

arreglo_1= np.random.randint(1,20,5)
arreglo_2= np.random.randint(1,20,5)

print(arreglo_1)
print(arreglo_2)

[14  5  6  5 13]
[17  9  4 16  8]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [ ]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

# Tu respuesta aquí
condicion = notas >= 6

print(condicion)

[ True  True  True False  True False  True False]
